### ISSUE TITLE
Editor mode

### ISSUE THREAD

**Issue by LeePower** [hcnode/AlexGallery#2]
Hi, thank you for the great work!
Would you tell me how to get into editor mode?
It shows on your screenshots of the upper right corner of preview screen
But I checkout the newest build, it's gone, any suggestion? Thanks!

**Comment by hcnode** [comment]
Sorry I add a "show edit button" option in the [ngGallery](https://github.com/hcnode/ngGallery), and I forget to set the option to default true in the AlexGallery, thank you for your reporting issue!

**Comment by LeePower** [comment]
Thank you! It's working now!
